service: minedec-geoportal
runtime: nodejs22
env_variables:
  ENVIRONMENT: "prod"
build_env_variables:
  NPM_CONFIG_LEGACY_PEER_DEPS: "true"

handlers:
  - url: /.*
    script: auto
    secure: always
